searchSpaceFile: search_space.json
trialCommand: python main.py
trialCodeDirectory: .
trialGpuNumber: 0
trialConcurrency: 4
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True